### ISSUE TITLE
Design task

### ISSUE THREAD

**Issue by archief2910** [opencodeiiita/DEresume#51]
Create a React.js webpage to explore and display existing Soul-Bound Tokens (SBTs) associated with the user's Metamask wallet. Additionally, link preexisting webpages in the frontend folder.

Tech Stack:
Frontend: React.js, Redux (optional), React Router
UI: Material-UI or Ant Design
Styling: CSS 
Details:

-Link Preexisting Pages:

Connect and link preexisting webpages in the frontend folder.
-SBT Explorer Webpage:

Develop a React.js webpage for exploring and displaying SBTs.
Implement Metamask connectivity for user authentication.
-Display User's SBTs:

Create a section displaying user-specific SBTs with relevant details.
-Responsive Design:

Ensure a responsive design for a seamless user experience.
Also make contributions in contributors folder.
You must also make a deploy.js file after hardhat compilation and select network as polygontestnet

**Comment by k7aditya** [comment]
claim

**Comment by archief2910** [comment]
@k7aditya its open for all you can work on it

**Comment by archief2910** [comment]
Contributors We have updated the task and the points for it

**Comment by kushal7201** [comment]
Claim

**Comment by Apoorv012** [comment]
claim

**Comment by sarthakvermaa** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by k7aditya** [comment]
claim

**Comment by k7aditya** [comment]
kindly assign the task to someone else
